name: First Docker CI

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code
      
    - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      name: Set envirement og TAGs
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Docker Build and push
      with:
        image: ilasiaq88/bedrock-action-test
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        tags: ${{ env.RELEASE_VERSION }}